version: "3.8"

services:
  backend:
    build: ./backend
    container_name: my-backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb+srv://salonikansal789:saloni@cluster0.ji59ihu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: my-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
